### ISSUE TITLE
fwa_indexpoint method

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwatlasbc#12]
see issue #11 discussion

does fwa_indexpoint find the nearest stream as the crow flies (i.e. regardless of whether it is in that stream's watershed) or does it find the nearest stream within the same watershed?

@smnorris can you comment?

**Comment by smnorris** [comment]
Nearest stream as the crow flies: https://github.com/smnorris/fwapg/blob/main/sql/functions/FWA_IndexPoint.sql

My use case was with hydrometric stations, the station locations are unreliable so I pull several nearby streams (within a given tolerance) and try and match based on stream/station name if possible.

**Comment by sebdalgarno** [comment]
Thanks @smnorris that makes sense. @joethorley I think "within a given tolerance" is important here, i.e. we should expect users to believe that the points they are providing are reasonably close to a stream (and therefore in the same watershed).

**Comment by smnorris** [comment]
In theory it should be possible to get fancy and use the raindrop method like the EPA service but would be a lot of work to implement https://www.epa.gov/waterdata/point-indexing-service

**Comment by joethorley** [comment]
That would be cool - maybe something for the future.
