### ISSUE TITLE
I think fwa_stream_to_blue_line_keys() should allow multiple streams and return a data frame of name streams

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/fwatlasbc#21]
In other words it should be renamed fwa_streams_to_blue_line_keys() and it should basically return the named streams that match including watershed_group_code

**Comment by sebdalgarno** [comment]
Sounds good. I think the only major downside to this is it breaks our vision of a piped workflow, i.e.
```
fwa_search_stream(:"sangan") %>%
     fwa_stream_to_blue_line_key() %>%
     fwa_blue_line_key_to_watershed() %>%
     fwa_get_stream_network()
```
But I do like it because it forces the user to deal with issues of multiple blue_line_keys being returned and deals with the issue of returning different object types

**Comment by sebdalgarno** [comment]
as a side note, I think given how many steps the above takes, it would be useful at some point to add a function that does this:
```
fwa_get_stream_network("Sangan River")
```
even if it is just for named streams

**Comment by joethorley** [comment]
It already gets broken by the fact that one stream can return more than 1 blue line key but can sort of be hacked by the following although better to filter before so no need to use first().

```
fwa_search_stream(:"sangan") %>%
     fwa_stream_to_blue_line_key() %>%
     use_series("blue_line_key") %>%
     first() %>%
     fwa_blue_line_key_to_watershed() %>%
     fwa_get_stream_network()
```

**Comment by joethorley** [comment]
And yes I totally agree with `fwa_get_stream_network()`.

**Comment by sebdalgarno** [comment]
I'll add a separate issue on fwa_get from gnis_name to discuss that
