### ISSUE TITLE
Why do stream rkms go further than the stream network.

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/fwatlasbc#24]
Consider the following two images of the stream network for a couple of watershed vs the stream rkms.
The rkms seem to go to the mountain top. This suggests to me that both are based on the DEM but the stream network cutoffs when it reaches a minimum watershed size.

Stream Network

![Screen Shot 2020-11-10 at 18 15 47](https://user-images.githubusercontent.com/613671/98855889-9ce17f80-2411-11eb-976b-e4d7e73ed9f7.png)

Rkms

![Screen Shot 2020-11-10 at 18 15 40](https://user-images.githubusercontent.com/613671/98855954-b387d680-2411-11eb-889d-e942af33bd8a.png)

**Comment by joethorley** [comment]
@smnorris - is this your understanding?

**Comment by smnorris** [comment]
Nothing in fwapg is based on the DEM, all features should be either existing features in the FWA or in the case of rkms, interpreted directly from the streams. That stream network image looks incomplete, are you filtering by order?

**Comment by joethorley** [comment]
I don't think I'm filtering by order but I'll look further into it.

FWIW this is an example when they do match (but incidentally the watershed seems wrong)

```r
blue_line_key <- 356364336

watershed <- fwatlasbc::fwa_blue_line_key_to_watershed(blue_line_key)

mapview::mapview(watershed)

stream_network <- fwatlasbc::fwa_get(watershed, "whse_basemapping.fwa_stream_networks_sp")

mapview::mapview(sf::st_zm(stream_network))

rkm <- fwatlasbc::fwa_rkm(blue_line_key, interval = 10)

mapview::mapview(sf::st_zm(rkm))

mapview::mapview(watershed) + mapview::mapview(sf::st_zm(stream_network)) + mapview::mapview(sf::st_zm(rkm))
```
