### ISSUE TITLE
Columbia rkm

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwatlasbc#32]
can't generate rkm with Columbia River blue_line_key
```
rkm <- fwatlasbc::fwa_rkm(blue_line_key = 356570372L)
```
error message
```
Error: API request failed [404]: Unable to read data from: fwa_locatealonginterval
```

**Comment by sebdalgarno** [comment]
also fails at source function
```
fwapgr::fwa_locate_along_interval(356570372L, start_measure = 100)
```

**Comment by smnorris** [comment]
Use the EPA tool for stream segments in USA lower 48. https://www.epa.gov/waterdata/point-indexing-service

**Comment by smnorris** [comment]
It should work for portions of the Columbia in BC, give it a start_measure near Trail.

**Comment by sebdalgarno** [comment]
thanks for quick response @smnorris - should we move the discussion over to https://github.com/smnorris/fwapg/issues/42 ?
