### ISSUE TITLE
Is it possible to specify projection of bbox?

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/fwatlasbc#5]

**Comment by sebdalgarno** [comment]
we could allow a vector without class bbox but assume it is 4326 in that case (and jsut pass directly to fwapgr and API without any conversion)

**Comment by joethorley** [comment]
yes I like that the default is 4326 but user can also pass an object of class bbox

**Comment by sebdalgarno** [comment]
this is no longer relevant as  user provides watershed polygon
